config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :contacts, :only => [:index, :show]  
  resources :contact_emails, :only => [:index, :show]
  
  match '/views/important', :to => 'contacts#important'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/privacy', :to => 'pages#privacy'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup', :to => 'users#new'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20101226210711
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base
	has_many :alternate_emails
	has_many :contacts
	has_many :contact_emails, :through => :contacts

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
            :length	=> { :maximum => 50 }
            
  validates :email, :presence => true,
            :format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }

  validates :password, :presence	=> true,
            :confirmation => true, :length	=> { :within => 6..40 }            

  before_save :encrypt_password


  # class methods
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  # public instance methods
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  # private instance methods
  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @contacts = @user.contacts.paginate(:page => params[:page])
    @alternate_emails = @user.alternate_emails
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign Up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def edit
    @title = "Edit User"
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user else
      @title = "Edit user"
      render 'edit'
    end
  end

  private
    def authenticate
      deny_access unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
  
end

app/views/users/_user.html.erb
<tr>
	<td><%= link_to user.name, user %></td>
	<td><%= user.email %></td>
	<td><%= user.contacts.count %></td>
</tr>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>
<div>
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>
<table>
	<tr>
		<td>Name</td>
		<td>Email</td>
		<td>Contacts</td>
	</tr>
	<%= render @users %>
</table>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
				Contacts for <%= @user.name %>
			</h1>
		<% unless @user.contacts.empty? %>
			<%= page_entries_info @contacts %>
			<%= will_paginate @contacts %>
			<table class="contacts" summary="User contacts">
				<tr>
					<td>ID</td>
					<td>Name</td>
					<td>Email Addresses</td>
					<td>Unread</td>
					<td></td>
				</tr>
				<%= render @contacts %>
			</table>
			<%= will_paginate @contacts %>
		<% end %>
		</td>

		<td class="sidebar round">
			<strong>User Information</strong><br />
			<strong>Name</strong> <%= @user.name %><br />
			<strong>Primary Email</strong> <%= @user.email %><br />
		<% unless @user.alternate_emails.empty? %>
			<strong>Alternate Email</strong> <%= render @alternate_emails %><br />
		<% end %>
			<strong>Contacts</strong> <%= @user.contacts.count %><br />
			<strong>Profile URL</strong> <%= link_to user_path(@user), @user %><br />
			<strong>All Contacts</strong> <%= link_to contacts_path, contacts_path %><br />
			<strong>Important Contacts</strong> <%= link_to views_important_path, views_important_path %>
			<strong>All Contact Emails</strong> <%= link_to contact_emails_path, contact_emails_path %>
		</td>
	</tr>
</table>